AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sentiment Analysis API

Resources:
  SentimentAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          NLTK_DATA: /var/task/nltk_data

  SentimentAnalysisApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: Sentiment Analysis API
        paths:
          /sentiment:
            post:
              x-amazon-apigateway-integration:
                uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/!Ref SentimentAnalysisFunction.Arn/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                requestParameters:
                  integration.request.querystring.text: method.request.querystring.text
        x-amazon-apigateway-authorization:
          type: NONE
q
