AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sentimentModel_serverless

  Sample SAM Template for sentimentModel_serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  SentimentAnalysisFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sentiment_analysis/
      Handler: app.analyze_sentiment
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SentimentAnalysis:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RequestParameters:
              method.request.querystring.yourQueryParamName: true

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SentimentAnalysisApi:
    Description: API Gateway endpoint URL for Prod stage for Sentiment Analysis function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
  SentimentAnalysisFunction:
    Description: Sentiment Analysis Lambda Function ARN
    Value: !GetAtt SentimentAnalysisFunction.Arn
  SentimentAnalysisFunctionIamRole:
    Description: Implicit IAM Role created for Sentiment Analysis function
    Value: !GetAtt SentimentAnalysisFunctionRole.Arn
